# docker build -t fschlatt/authorship-verification-trivial:0.0.1 .
FROM fschlatt/natural-language-processing-exercises:0.0.1

RUN pip3 install pandas
ADD ngramkf.py /code/ngramkf.py
# ADD ./knn_classifier/. /code/knn_classifier/

ENTRYPOINT ["python", "/code/ngramkf.py"]
