# docker build -t fschlatt/authorship-verification-trivial:0.0.1 .
FROM fschlatt/natural-language-processing-exercises:0.0.1

ADD assignment2.py /code/assignment2.py

ENTRYPOINT ["python3", "/code/assignment2.py"]
