# docker build -t fschlatt/authorship-verification-trivial:0.0.1 .
FROM fschlatt/natural-language-processing-exercises:0.0.1

RUN pip install langid
ADD assi2.py /code/assi2.py

ENTRYPOINT ["python3", "/code/assi2.py"]
