# docker build -t fschlatt/authorship-verification-trivial:0.0.1 .
FROM fschlatt/natural-language-processing-exercises:0.0.1

WORKDIR /app

RUN pip install langid pandas tqdm tira-rest-api-client

COPY assi2.py /app/assi2.py

CMD ["python", "assi2.py"]
