# docker build -t fschlatt/authorship-verification-trivial:0.0.1 .
FROM Tirthkumar1/natural-language-processing-exercises:0.0.1

ADD assi2.py /code/assi2.py

ENTRYPOINT ["python3", "/code/assi2.py"]
